"""booking

Revision ID: 27c335bf11bd
Revises: f2afba011e77
Create Date: 2025-10-08 16:48:03.766483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c335bf11bd'
down_revision = 'e46e60bca37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookingmodel',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('guests_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('BOOKED', 'CANCELLED', 'ACTIVE', name='bookingstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookingmodel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookingmodel_cafe_id'), ['cafe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookingmodel_user_id'), ['user_id'], unique=False)

    op.create_table('booking_dishes',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookingmodel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id', 'dish_id')
    )
    op.create_table('booking_slots',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookingmodel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['time_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id', 'slot_id')
    )
    op.create_table('booking_tables',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookingmodel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id', 'table_id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index('ix_actions_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index('ix_actions_id', ['id'], unique=False)

    op.drop_table('booking_tables')
    op.drop_table('booking_slots')
    op.drop_table('booking_dishes')
    with op.batch_alter_table('bookingmodel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookingmodel_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookingmodel_cafe_id'))

    op.drop_table('bookingmodel')
    # ### end Alembic commands ###
