"""actions

Revision ID: e46e60bca37b
Revises: f2afba011e77
Create Date: 2025-10-06 11:25:03.839811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46e60bca37b'
down_revision = 'f2afba011e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index('ix_actions_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index('ix_actions_id', ['id'], unique=False)

    # ### end Alembic commands ###
