"""slot table

Revision ID: 3855a72075c2
Revises: f2afba011e77
Create Date: 2025-10-03 17:12:17.041402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3855a72075c2'
down_revision = 'f2afba011e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
