"""cafe name mandatory added

Revision ID: 46b65969a8aa
Revises: 2eeef23cb0ad
Create Date: 2025-09-21 23:31:41.281743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b65969a8aa'
down_revision = '2eeef23cb0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.drop_index('ix_cafe_name')
        batch_op.create_index(batch_op.f('ix_cafe_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cafe_name'))
        batch_op.create_index('ix_cafe_name', ['name'], unique=False)

    # ### end Alembic commands ###
