"""add unique constraint for cafe and dish

Revision ID: 7526c0aa2d3b
Revises: 3b1c5c2efbc0
Create Date: 2025-09-30 00:41:24.959080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7526c0aa2d3b'
down_revision = '3b1c5c2efbc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.create_unique_constraint('uc_dish_cafe_id_name_unique', ['cafe_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.drop_constraint('uc_dish_cafe_id_name_unique', type_='unique')

    # ### end Alembic commands ###
