"""tablemodel

Revision ID: c8387b2d266c
Revises: fa3ab3f165ea
Create Date: 2025-09-26 10:28:49.165269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8387b2d266c'
down_revision = 'fa3ab3f165ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cafe_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_cafe_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_cafe_phone'), ['phone'], unique=False)

    op.create_table('cafe_managers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'cafe_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
        batch_op.drop_index('ix_user_username')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
        batch_op.drop_column('active')

    op.drop_table('cafe_managers')
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cafe_phone'))
        batch_op.drop_index(batch_op.f('ix_cafe_name'))
        batch_op.drop_index(batch_op.f('ix_cafe_address'))

    op.drop_table('cafe')
    # ### end Alembic commands ###
